In [2]:
import pandas as pd

#load the datasets:
df = pd.read_csv('Salary_Data.csv')

print(len(df)) # Gives no of rows
print(len(df.columns)) # Gives no of columns
df.shape

6704
6

(6704, 6)

In [2]:
df.shape

(6704, 6)

In [7]:
df.sample(5) # Extracts the top 5 data from the df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
3317,27.0,Female,Bachelor's Degree,Software Engineer,3.0,70000.0
3523,29.0,Female,Master's Degree,Web Developer,4.0,65000.0
1925,29.0,Female,Bachelor's Degree,Front end Developer,4.0,90000.0
3348,42.0,Male,Master's Degree,Product Manager,14.0,180000.0
4119,41.0,Female,Master's Degree,Human Resources Manager,13.0,140000.0

In [8]:
df.columns # Gives all the column names of the dataset

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='str')

In [9]:
df.info() # gives quick description of our dataset

<class 'pandas.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   str
 2   Education Level      6701 non-null   str
 3   Job Title            6702 non-null   str
 4   Years of Experience  6701 non-null   float64
 5   Salary               6699 non-null   float64
dtypes: float64(3), str(3)
memory usage: 552.7 KB


Descriptive analysis

In [10]:
df.describe() # Use df.describe() to check the distribution of values.

               Age  Years of Experience         Salary
count  6702.000000          6701.000000    6699.000000
mean     33.620859             8.094687  115326.964771
std       7.614633             6.059003   52786.183911
min      21.000000             0.000000     350.000000
25%      28.000000             3.000000   70000.000000
50%      32.000000             7.000000  115000.000000
75%      38.000000            12.000000  160000.000000
max      62.000000            34.000000  250000.000000

In [11]:
df.describe(include='object') # Use df.describe() to check the distribution of values.

C:\Users\acer\AppData\Local\Temp\ipykernel_976\2069285522.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object') # Use df.describe() to check the distribution of values.

       Gender    Education Level          Job Title
count    6702               6701               6702
unique      3                  7                193
top      Male  Bachelor's Degree  Software Engineer
freq     3674               2267                518

In [12]:
# Summary statistics for categorical columns
print(df.describe(include='float'))
print()
print()
print()
print(df.describe(include='object'))

               Age  Years of Experience         Salary
count  6702.000000          6701.000000    6699.000000
mean     33.620859             8.094687  115326.964771
std       7.614633             6.059003   52786.183911
min      21.000000             0.000000     350.000000
25%      28.000000             3.000000   70000.000000
50%      32.000000             7.000000  115000.000000
75%      38.000000            12.000000  160000.000000
max      62.000000            34.000000  250000.000000



       Gender    Education Level          Job Title
count    6702               6701               6702
unique      3                  7                193
top      Male  Bachelor's Degree  Software Engineer
freq     3674               2267                518

C:\Users\acer\AppData\Local\Temp\ipykernel_976\1117183669.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include='object'))

 Gender
count = 6702 → There are 6702 entries in the Gender column (2 missing values).

unique = 3 → There are 3 unique gender categories (e.g., 'Male', 'Female', maybe 'Other' or 'Non-Binary').

top = 'Male' → The most common gender is 'Male'.

freq = 3674 → 'Male' appears 3674 times.

count = 6701 → 6701 entries (3 missing value).

unique = 7 → 7 distinct education levels (e.g., High School, Bachelor's, Master's, PhD, etc.).

top = 'Bachelor's Degree' → Most frequent education level.

freq = 2267 → 'Bachelor's Degree' appears 2267 times.

In [13]:
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [14]:
df.isnull().sum() # Gives the sum of no. of null values present in our column

Age                    2
Gender                 2
Education Level        3
Job Title              2
Years of Experience    3
Salary                 5
dtype: int64

In [15]:
df.shape

(6704, 6)

the dropna() function in Pandas is used to remove missing values (i.e., NaNs) from a DataFrame or Series.

What It Does:
Removes all rows that contain at least one NaN (missing value).

Returns a new DataFrame with only complete rows (no missing data).

In [16]:
df_cleaned = df.dropna() # Removes the row that contains at leat one null values
print(f"Remaining rows: {len(df_cleaned)}")
df_cleaned.shape

Remaining rows: 6698

(6698, 6)

In [ ]:
#checking again to confirm it's clean:

In [17]:

print(df_cleaned.isnull().sum())

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [18]:
df_cleaned

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [19]:
print("\nData Types:")
print(df_cleaned.dtypes)
df_cleaned.info()

Data Types:
Age                    float64
Gender                     str
Education Level            str
Job Title                  str
Years of Experience    float64
Salary                 float64
dtype: object
<class 'pandas.DataFrame'>
Index: 6698 entries, 0 to 6703
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6698 non-null   float64
 1   Gender               6698 non-null   str
 2   Education Level      6698 non-null   str
 3   Job Title            6698 non-null   str
 4   Years of Experience  6698 non-null   float64
 5   Salary               6698 non-null   float64
dtypes: float64(3), str(3)
memory usage: 604.5 KB

In [20]:
# Summary statistics for categorical columns
print(df_cleaned.describe())
print()
print()
print()
print(df_cleaned.describe(include='object'))

               Age  Years of Experience         Salary
count  6698.000000          6698.000000    6698.000000
mean     33.623022             8.095178  115329.253061
std       7.615784             6.060291   52789.792507
min      21.000000             0.000000     350.000000
25%      28.000000             3.000000   70000.000000
50%      32.000000             7.000000  115000.000000
75%      38.000000            12.000000  160000.000000
max      62.000000            34.000000  250000.000000



       Gender    Education Level          Job Title
count    6698               6698               6698
unique      3                  7                191
top      Male  Bachelor's Degree  Software Engineer
freq     3671               2265                518

C:\Users\acer\AppData\Local\Temp\ipykernel_976\4229294510.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df_cleaned.describe(include='object'))

In [21]:
df_cleaned

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [25]:
df_cleaned[['Salary']]

        Salary
0      90000.0
1      65000.0
2     150000.0
3      60000.0
4     200000.0
...        ...
6699  200000.0
6700   50000.0
6701   55000.0
6702  140000.0
6703   35000.0

[6698 rows x 1 columns]

In [26]:
# 1. Find the maximum salary value
max_salary = df_cleaned['Salary'].max()
print(max_salary)

250000.0

In [ ]:
df_cleaned[df_cleaned['Salary'] == max_salary]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
30,50.0,Male,Bachelor's,CEO,25.0,250000.0
83,52.0,Male,PhD,Chief Technology Officer,24.0,250000.0
5001,45.0,Male,Bachelor's Degree,Financial Manager,21.0,250000.0

The age of the person that has max salary should be grater than 40

The years of experience of the person that has max salary should be grater than 20

In [28]:
# 2. Get the row(s) with that maximum salary
max_salary_row = df_cleaned[df_cleaned['Salary'] == max_salary]
# 3. Display the result
print("Employee(s) with Maximum Salary:")
max_salary_row

Employee(s) with Maximum Salary:

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
30,50.0,Male,Bachelor's,CEO,25.0,250000.0
83,52.0,Male,PhD,Chief Technology Officer,24.0,250000.0
5001,45.0,Male,Bachelor's Degree,Financial Manager,21.0,250000.0

The gender of having max_salary wpuld be Male

df_cleaned['Salary'] == max_salary

This part creates a Boolean Series.

It checks each row's salary in the Salary column and compares it to the max_salary value.

Result: a Series of True or False values.

In [29]:
i=df_cleaned['Salary'] == max_salary
df_cleaned[i]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
30,50.0,Male,Bachelor's,CEO,25.0,250000.0
83,52.0,Male,PhD,Chief Technology Officer,24.0,250000.0
5001,45.0,Male,Bachelor's Degree,Financial Manager,21.0,250000.0

In [32]:
# 1. Get unique job titles and their counts
job_title_counts = df_cleaned['Job Title'].value_counts()
print(job_title_counts)

# 2. Display the result
# print(" Job Title List and Counts:")
# print(job_title_counts)

Job Title
Software Engineer                518
Data Scientist                   453
Software Engineer Manager        376
Data Analyst                     363
Senior Project Engineer          318
                                ...
Junior Research Scientist          1
Senior HR Specialist               1
Junior Operations Coordinator      1
Junior Financial Advisor           1
Social Media Man                   1
Name: count, Length: 191, dtype: int64

In [34]:
# Get the job title that appears the most
most_common_job_title = df_cleaned['Job Title'].value_counts().idxmax() 
print(most_common_job_title)# Index of max value in each column
# count = df_cleaned['Job Title'].value_counts().max() # Max value in each column
# most_common_job_title = "Software Engineer"
# count = 518

# print(f"Most common job title: {most_common_job_title} ({most_common_job_title} occurrences)")
# print(f"Most common job title: {count} ({count} occurrences)")

Software Engineer

In [37]:
most_common_title = 'Software Engineer'

# 1. Filter rows where Job Title is 'Software Engineer'
software_engineers = df_cleaned[df_cleaned['Job Title'] == most_common_title]
print(software_engineers)
# # 2. Find max salary among Software Engineers
se_max_salary = software_engineers['Salary'].max()
print(se_max_salary)

# # # # # # 3. Get row(s) with that max salary
top_earner = software_engineers[software_engineers['Salary'] == se_max_salary]

# # # # # # 4. Show result
print(f" Highest Paid '{most_common_title}':")
print()
print()
print(top_earner)

       Age  Gender    Education Level          Job Title  Years of Experience  \
0     32.0    Male         Bachelor's  Software Engineer                  5.0
376   28.0  Female         Bachelor's  Software Engineer                  3.0
380   29.0  Female         Bachelor's  Software Engineer                  4.0
384   31.0  Female         Bachelor's  Software Engineer                  6.0
388   29.0  Female         Bachelor's  Software Engineer                  4.0
...    ...     ...                ...                ...                  ...
6191  27.0    Male  Bachelor's Degree  Software Engineer                  3.0
6205  27.0    Male  Bachelor's Degree  Software Engineer                  3.0
6219  27.0    Male  Bachelor's Degree  Software Engineer                  3.0
6233  27.0    Male  Bachelor's Degree  Software Engineer                  3.0
6247  27.0    Male  Bachelor's Degree  Software Engineer                  3.0

        Salary
0      90000.0
376   125000.0
380   140000.0
384   155000.0
388   140000.0
...        ...
6191   80000.0
6205   80000.0
6219   80000.0
6233   80000.0
6247   80000.0

[518 rows x 6 columns]
197000.0
 Highest Paid 'Software Engineer':


      Age  Gender    Education Level          Job Title  Years of Experience  \
952  42.0  Female  Bachelor's Degree  Software Engineer                 13.0

       Salary
952  197000.0

In [ ]:
software_engineers[software_engineers['Salary'] == se_max_salary][['Gender','Job Title','Salary']]

The gender that receives the maximum salary in software development job title should be Female.

In [ ]:
df_cleaned

In [ ]:
# 1. Find the maximum age
max_age = df_cleaned['Age'].max() # Receives the max age from the age column
print(max_age)

# 2. Get the row(s) where Age equals max_age
oldest_person = df_cleaned[df_cleaned['Age'] == max_age] # Find the peoples who have age == max_age

# 3. Display the result
print(f" Person(s) with Maximum Age ({max_age} years):")
oldest_person # Prints the row having age == max_age

In [ ]:
df_cleaned['Gender'].value_counts()

In [ ]:
#average salary by gender:
avg_salary_gender = df_cleaned.groupby('Gender')['Salary'].mean().sort_values(ascending=False)
print(avg_salary_gender)
# df_cleaned.groupby('Gender')  This groups the rows of the DataFrame by the Gender column.
# ['Salary'] After grouping, we pick the salary column from each group and calculate the mean (average) salary
# avg_salary_gender.sample(10)

#############################
.groupby('Gender')
This groups the entire data based on unique values in the 'Gender' column.

In [ ]:
edu_counts = df_cleaned['Education Level'].value_counts()
print(edu_counts)

In [ ]:
# Count how many have "Master's Degree" in Education Level
master_count = df_cleaned[df_cleaned['Education Level'] == "Master's Degree"].shape[0]

# print(f"Number of people with Master's Degree: {master_count}")
master_count

In [ ]:
#find the age of people under 30  to 40:
import numpy as np
age_30_40 = df_cleaned[np.logical_and((df_cleaned['Age'] >= 30) , (df_cleaned['Age'] <= 40))]
# age_30_40 = df_cleaned[~(df_cleaned['Age'] >= 30)]
# | => or
# ~ => not
age_30_40

In [ ]:
# Filter Job title aged between 30 and 40
abc = df_cleaned[df_cleaned['Age'].between(30,40)]
print(abc.head(10))
abc.shape

In [ ]:
#average salary in age 30-40 :
avg_salary_30_40 = age_30_40['Salary'].mean()
print(f" Average salary (age 30–40): {avg_salary_30_40}")

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['A', 'B', 'C']
})

df2 = pd.DataFrame({
    'id': [1, 2, 4],
    'name': [5000, 6000, 7000]
})

result = pd.merge(df1, df2, how='inner', on='id')
print(result)

In [ ]:
df1 = pd.DataFrame({'A': [1, 2,3,4], 'B':[5,6,7,8]})
df2 = pd.DataFrame({'A': [3, 4],"B":[5,6]})

pd.concat([df1, df2], axis=1)

In [ ]:
df1

In [ ]:
df_cleaned

In [ ]:
df_cleaned.to_csv('df_cleaned.csv', index=False)

In [ ]:
df_cleaned.duplicated().sum()

In [ ]:
df_cleaned.drop_duplicates(inplace=True)

In [ ]:
df_cleaned.duplicated().sum()

In [ ]:
df_cleaned.shape